CREATE TABLE employee
(
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name           VARCHAR2(255) NOT NULL,
    employee_id         VARCHAR2(100) NOT NULL UNIQUE,
    job_title           VARCHAR2(255),
    department          VARCHAR2(255),
    hire_date           DATE,
    employment_status   VARCHAR2(50),
    contact_information VARCHAR2(255),
    address             VARCHAR2(255),
    PRIMARY KEY (id)
);