CREATE TABLE employee
(
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name           VARCHAR2(255) NOT NULL,
    employee_id         VARCHAR2(100) NOT NULL UNIQUE,
    job_title           VARCHAR2(255),
    department          VARCHAR2(255),
    hire_date           DATE,
    employment_status   VARCHAR2(50),
    contact_information VARCHAR2(255),
    address             VARCHAR2(255),
    PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- Create the USER table
CREATE TABLE app_user
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR2(50) NOT NULL UNIQUE,
    password   VARCHAR2(255) NOT NULL,
    email      VARCHAR2(100) NOT NULL UNIQUE,
    department VARCHAR2(50),
    is_active  NUMBER(1) DEFAULT 1 NOT NULL
);

-- Create the USER_ROLE join table
CREATE TABLE user_role
(
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE
);